# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20161127_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Starter',
        ),
        migrations.DeleteModel(
            name='Bevages',
        ),
        migrations.RemoveField(
            model_name='sweets',
            name='menu_id',
        ),
        migrations.DeleteModel(
            name='Sweets',
        ),
    ]
