# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_auto_20161128_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Bevage',
        ),
        migrations.RenameModel(
            old_name='Bevages',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='Sweets',
            new_name='Sweet',
        ),
    ]
